version: "3"
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    user: root
    volumes:
      - /environment/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - /environment/vault/logs:/vault/logs
      - /environment/vault/file:/vault/file
      - /environment/vault/config:/vault/config
    cap_add:
     - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbitmq"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  sonarqube:
    image: "sonarqube:7.8-community"
    hostname: "sonarqube"
    container_name: "sonarqube"
    ports:
      - "9000:9000"
      - "9001:9001"