version: "3"
services:
  # config-server
  # service-discovery
  # gateway
  # sample-service
  # jenkins
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./enviroment/vault/logs:/vault/logs
      - ./enviroment/vault/file:/vault/file
      - ./enviroment/vault/config:/vault/config
    cap_add:
     - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbitmq"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  sonarqube:
    image: "sonarqube:7.8-community"
    hostname: "sonarqube"
    container_name: "sonarqube"
    ports:
      - "9000:9000"
      - "9001:9001"