spring:
  application:
    name: api-gateway

eureka:
  client:
    fetch-registry: true
    service-url:
      - http://localhost:8761/eureka

server:
  port: 80

zuul:
  strip-prefix: false
  routes:
    sample-service:
      path: /sample-service/**
      service-id: sample-service